api/urls.py
# from rest_framework import routers
# from api import views
# router = routers.DefaultRouter()
# router.register(r'rate', views.RateViewSet)
from django.urls import path

from api import views

urlpatterns = [
    # path('snippets/', views.sn),
    path('rate/<int:user_id>', views.rate_detail),
    path('comment/<int:user_id>', views.comment_detail),
    path('collect/<int:user_id>', views.collect_detail),
]

movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("user.urls")),
        path("api/", include("api.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

user/urls.py
from django.urls import path
from user import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout, name="logout"),
    path("movie/<int:movie_id>/", views.movie, name="movie"),
    path("score/<int:movie_id>/", views.score, name="score"),
    path("comment/<int:movie_id>/", views.make_comment, name="comment"),
    path("collect/<int:movie_id>/", views.collect, name="collect"),
    path("decollect/<int:movie_id>/", views.decollect, name="decollect"),
    path("personal/", views.personal, name="personal"),
    path("delete_comment/<int:comment_id>", views.delete_comment, name="delete_comment"),
    path("delete_rate/<int:rate_id>", views.delete_rate, name="delete_rate"),

    path("choose_tags/", views.choose_tags, name="choose_tags"),
    path("all_tags/", views.all_tags, name="all_tags"),
    path("all_actors/", views.all_actors, name="all_actors"),
    path("all_directors/", views.all_directors, name="all_directors"),
    path("all_companies/", views.all_companies, name="all_companies"),
    
    path("actor/<int:actor_id>/", views.actor, name="actor"),
    path("director/<int:director_id>/", views.director, name="director"),
    path("clear_cache/", views.clear_cache, name="clear_cache"),

    path("search/", views.search, name="search"),
    path("actor_search/", views.actor_search, name='actor_search'),
    path("director_search/", views.director_search, name='director_search'),
    path("company_search/", views.company_search, name='company_search'),
    
]

user/models.py
from django.db import models
from django.db.models import Avg
from django.core.validators import MinValueValidator, MaxValueValidator


class User(models.Model):
    username = models.CharField(max_length=255, unique=True, verbose_name="用户名")
    password = models.CharField(max_length=255, verbose_name="密码")
    email = models.EmailField(verbose_name="邮箱")

    class Meta:
        db_table = 'user_user'
        verbose_name_plural = "普通用户"
        verbose_name = "普通用户"

    def __str__(self):
        return self.username


class Tags(models.Model):
    name = models.CharField(max_length=255, verbose_name="电影标签", unique=True)

    class Meta:
        db_table = 'user_tags'
        verbose_name = "电影标签"
        verbose_name_plural = "电影标签"

    def __str__(self):
        return self.name



# 公司信息管理
class Company(models.Model):
    name = models.CharField(max_length=255, verbose_name='公司名称', unique=True)    # cx 0623 保证唯一性
    city = models.CharField(max_length=64, verbose_name='所在城市')
    # 增加了"company"的别名“公司信息”  cx
    class Meta:
        db_table = 'user_company'
        verbose_name = "公司信息"
        verbose_name_plural = "公司信息"

    def __str__(self):
        return self.name


# 新增的演员信息管理  cx
class Actor(models.Model):
    name = models.CharField(verbose_name="演员姓名", max_length=255)
    gender = models.CharField(verbose_name="性别", max_length=4)
    birthday = models.DateField(verbose_name="生日")
    introduction = models.TextField(verbose_name="简介")
    nationality = models.CharField(verbose_name="国籍", max_length=255)
    prize = models.CharField(verbose_name="获奖信息", max_length=255)
    image_link = models.FileField(verbose_name="演员照片", max_length=255, upload_to='actor_photo',null=True, blank=True)

    class Meta:
        db_table = 'user_actor'
        verbose_name = "演员信息"
        verbose_name_plural = "演员信息"

    def __str__(self):
        return self.name
    

# 新增的导演信息管理  cx
class Director(models.Model):
    name = models.CharField(verbose_name="导演姓名", max_length=255)
    gender = models.CharField(verbose_name="性别", max_length=4)
    birthday = models.DateField(verbose_name="生日")
    introduction = models.TextField(verbose_name="简介")
    nationality = models.CharField(verbose_name="国籍", max_length=255)
    prize = models.CharField(verbose_name="获奖信息", max_length=255)
    image_link = models.FileField(verbose_name="导演照片", max_length=255, upload_to='director_photo',null=True, blank=True)

    class Meta:
        db_table = 'user_director'
        verbose_name = "导演信息"
        verbose_name_plural = "导演信息"

    def __str__(self):
        return self.name



class Movie(models.Model):
    tags = models.ManyToManyField(Tags, verbose_name='电影标签')      # 删掉了最后的 , blank = True cx0622
    collect = models.ManyToManyField(User, verbose_name="收藏用户",null=True,blank=True)   # 删掉了最后的 , blank = True cx0622
    name = models.CharField(verbose_name="电影名称", max_length=255, unique = True)
    director = models.ManyToManyField(Director, through='MovieDirector', verbose_name="导演", max_length=255)         # cx 0622
    country = models.CharField(verbose_name="国家/地区", max_length=255)
    years = models.DateField(verbose_name='上映时间')
    actor = models.ManyToManyField(Actor, through='MovieActor',verbose_name="演员", max_length=1024)          # cx 0622
    d_rate = models.DecimalField(verbose_name="电影数据库评分", max_digits=3, decimal_places=1, null=True, blank=True, 
        validators=[
            MinValueValidator(1),  # 设置最小值为1
            MaxValueValidator(10)   # 设置最大值为10
        ])
    intro = models.TextField(verbose_name="情节简介")
    num = models.IntegerField(verbose_name="浏览数量", default=0, validators=[
            MinValueValidator(0)])          # 设置最小值为0
    image_link = models.FileField(verbose_name="宣传图", max_length=255, upload_to='movie_cover', null=True, blank=True)

    duration = models.IntegerField(verbose_name='电影时长', null=True, validators=[
            MinValueValidator(0)])          # 设置最小值为0
    state = models.CharField(verbose_name="上映状态",max_length=20)
    language = models.CharField(verbose_name="语言",max_length=20)
    company = models.ForeignKey(Company,verbose_name="涉及公司",on_delete=models.CASCADE)


    @property
    def movie_rate(self):
        movie_rate = Rate.objects.filter(movie_id=self.id).aggregate(Avg('mark'))['mark__avg']
        return movie_rate or '暂无评分'

    class Meta:
        db_table = 'user_movie'
        verbose_name = "电影信息"
        verbose_name_plural = "电影信息"

    def __str__(self):
        return self.name



# sjy加入 0623
class MovieActor(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.RESTRICT, verbose_name="电影")
    actor = models.ForeignKey(Actor, on_delete=models.RESTRICT, verbose_name="演员")
    duty = models.TextField(verbose_name="饰演角色")

    class Meta:
        # 定义数据库约束名称，确保它们与 SQL 脚本中的相匹配（如果需要）
        db_table = 'user_movie_actor'  # 指定数据库中的表名称
        verbose_name = "电影与演员关系"
        verbose_name_plural = "电影与演员关系"
        unique_together = (('movie', 'actor', 'duty'),)     # cx 0623，保证唯一性

    def __str__(self):
        return f"{self.movie.name} - {self.actor.name}"



class MovieDirector(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.RESTRICT, verbose_name="电影")
    director = models.ForeignKey(Director, on_delete=models.RESTRICT, verbose_name="导演")
    duty = models.TextField(verbose_name="工作职责")

    class Meta:
        # 定义数据库约束名称，确保它们与 SQL 脚本中的相匹配（如果需要）
        db_table = 'user_movie_director'  # 指定数据库中的表名称
        verbose_name = "电影与导演关系"
        verbose_name_plural = "电影与导演关系"
        unique_together = (('movie', 'director', 'duty'),)     # cx 0623，保证唯一性

    def __str__(self):
        return f"{self.movie.name} - {self.director.name}"


# # cx 0624
# class MovieCompany(models.Model):
#     movie = models.ForeignKey(Movie, on_delete=models.RESTRICT, verbose_name="电影")
#     company = models.ForeignKey(Company, on_delete=models.RESTRICT, verbose_name="公司")

#     class Meta:
#         # 定义数据库约束名称，确保它们与 SQL 脚本中的相匹配（如果需要）
#         db_table = 'user_movie_company'  # 指定数据库中的表名称
#         verbose_name = "电影与公司关系"
#         verbose_name_plural = "电影与公司关系"
#         unique_together = (('movie', 'company'),)     # cx 0623，保证唯一性

#     def __str__(self):
#         return f"{self.movie.name} - {self.company.name}"


# # cx 0624
# class MovieTag(models.Model):
#     movie = models.ForeignKey(Movie, on_delete=models.RESTRICT, verbose_name="电影")
#     tag = models.ForeignKey(Tags, on_delete=models.RESTRICT, verbose_name="标签")

#     class Meta:
#         # 定义数据库约束名称，确保它们与 SQL 脚本中的相匹配（如果需要）
#         db_table = 'user_movie_tags'  # 指定数据库中的表名称
#         verbose_name = "电影与标签关系"
#         verbose_name_plural = "电影与标签关系"
#         unique_together = (('movie', 'tag'),)     # cx 0623，保证唯一性

#     def __str__(self):
#         return f"{self.movie.name} - {self.tag.name}"


class Rate(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="电影ID")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户名")
    mark = models.FloatField(verbose_name="评分", validators=[
            MinValueValidator(1),  # 设置最小值为1
            MaxValueValidator(10)   # 设置最大值为10
        ])
    create_time = models.DateTimeField(verbose_name="评分时间", auto_now_add=True)

    @property
    def avg_mark(self):
        average = Rate.objects.all().aggregate(Avg('mark'))['mark__avg']
        return average

    class Meta:
        db_table = 'user_rate'
        verbose_name = "评分信息"
        verbose_name_plural = "评分信息"
        unique_together = (('movie', 'user'),)           # cx 0623，保证唯一性（用户对一个电影只能有一个评分）



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户名")
    content = models.CharField(max_length=255, verbose_name="评论内容", blank=False, null=False)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="电影")

    class Meta:
        db_table = 'user_comment'
        verbose_name = "评论信息"
        verbose_name_plural = "评论信息"



# class Collect(models.Model):
#     movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='电影')
#     user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户名')

#     class Meta:
#         db_table = 'user_movie_collect'
#         verbose_name = "收藏信息"
#         verbose_name_plural = "收藏信息"

user/forms.py
from django import forms

from .models import *


class Login(forms.Form):
    username = forms.CharField(
        label="名字",
        max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control required"}),
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={"class": "form-control required"}),
    )


class Edit(forms.ModelForm):
    class Meta:
        model = User
        fields = ["password", "username", "email"]
        labels = {
            "password": "密码",
            "name": "名字",
            "email": "邮箱",
        }
        widgets = {
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
        }

        def clean_name(self):
            name = self.cleaned_data.get("name")
            result = User.objects.filter(name=name)
            if result:
                raise forms.ValidationError("Name already exists")
            return name


class RegisterForm(forms.Form):
    username = forms.CharField(
        label="Name(Not repeatable)",
        max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    email = forms.EmailField(
        label="Mailbox", widget=forms.EmailInput(attrs={"class": "form-control"})
    )
    password1 = forms.CharField(
        label="Password",
        max_length=128,
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )

    def clean_username(self):
        username = self.cleaned_data.get("username")

        if len(username) < 6:
            raise forms.ValidationError(
                "Your username must be at least 6 characters long."
            )
        elif len(username) > 50:
            raise forms.ValidationError("Your username is too long.")
        else:
            filter_result = User.objects.filter(username=username)
            if len(filter_result) > 0:
                raise forms.ValidationError("Your username already exists.")
        return username

    def clean_name(self):
        name = self.cleaned_data.get("name")
        filter_result = User.objects.filter(name=name)
        if len(filter_result) > 0:
            raise forms.ValidationError("Your name already exists.")
        return name

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if len(password1) < 6:
            raise forms.ValidationError("Your password is too short.")
        elif len(password1) > 20:
            raise forms.ValidationError("Your password is too long.")
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Password mismatch. Please enter again.")
        return password2

user/templates/user/actors.html
<!-- 新增的导演浏览界面 cx 20240613 -->
<!-- 应该要参考user/templates/index.html的line33~58 -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- <div class="col-md-8 content-left"> -->
    <!-- content artical 的定义在一堆css里面 -->
    <!-- 表格的容器的宽度占总宽度的8/12 -->

<div class="col-md-8 content-left" style="width: 100%;">

    <div class="albums">
        <h1>演员信息</h1>
    </div>

    <!-- cx0622修改了前端，支持两列显示，增加了一些空格 -->
    {% for actor in actors %}
        <div class="artical">
            <div class="artical-head">
                <h2>&nbsp;&nbsp;<a href="{% url 'actor' actor.id %}">{{ actor.name }}</a></h2>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
            <div class="artical-info">
                <p><strong>&nbsp;&nbsp;&nbsp;&nbsp;性别:</strong> {{ actor.gender }}</p>
                <p><strong>&nbsp;&nbsp;&nbsp;&nbsp;出生日期:</strong> {{ actor.birthday }}</p>
                <p><strong>&nbsp;&nbsp;&nbsp;&nbsp;国籍:</strong>{{ actor.nationality }}</p>
            </div>
        </div>
    {% endfor %}

    <!-- sjy0621新增 -->
    <div class="clearfix"></div>
    
    <!-- pagenate -->
    <div class="pagenate">
        <ul>
            {% for l in  actors.paginator.page_range %}
                {% if l <= actors.number|add:5 and l >= actors.number|add:-5 %}
                    {% if actors.number == l %}
                        <li class="page-active"><span>{{ l }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            {% if movies.has_next %}
                <li class="next"><a href="?page={{ actors.next_page_number }}">Next Page</a></li>
            {% endif %}
        </ul>
    </div>
    <!-- pagenate -->

</div>

{% endblock %}

user/templates/user/base_show.html
<!-- 首页 -->
{% extends 'base.html' %}
{% block right-panel-content %}
    <table class="table">
        <thead>
        <tr>
            {% block th_name  %}
                {% endblock %}
        </tr>
        </thead>
        <tbody>
        {% for i in item %}
            <div class="modal" id="#confirm-modal-{{ i.id }}">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Delete</h4>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete it?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            {% block modal %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
            <tr>
            {% block th_value %}
            {% endblock  %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- Button trigger modal -->
    <!-- Modal -->
{% endblock %}

user/templates/user/details.html
<!-- 电影详情界面 -->
{% extends 'base.html' %}
{% load grav_tag %}
{% block content %}
<style>
    .artical-details-info-right p a{
        color: #4cb4cc;
    }
</style>
    <div class="col-md-8 content-left" style="width: 100%;">
        <!-- artical-single-page -->
        <div class="artical-details">
            <h2>{{ movie.name }} </h2>
            <!-- artical-details-info -->
            <div class="artical-details-info">
                <div class="artical-details-info-left">
                    <a href="#"><img src="{{ MEDIA_URL }}{{ movie.image_link }}" title="name"/></a>
                </div>
                <div class="artical-details-info-right">
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>标签：</strong> {% for tag in movie.tags.all %}
                                <a href="{% url 'index' %}?tag_id={{ tag.id }}">{{ tag.name }}</a>
                            {% endfor %}
                            </p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>发布时间：</strong> {{ movie.years }}</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>电影时长：</strong> {{ movie.duration }} 分钟</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>上映状态：</strong>{{ movie.state }}</p>
                        </div>
                       
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>上映国家：</strong> {{ movie.country }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>语言：</strong> {{ movie.language }}</p>
                        </div>
                    </div>
                    
                    <p><strong>公司：</strong>{{ movie.company.name }}</p>

                    <!-- sjy 0622 -->
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>导演：</strong>
                                {% for director_role in director_roles %}
                                    <p><a href="{% url 'director' director_role.director.id %}">{{ director_role.director.name }}</a>  担任  {{ director_role.duty }}</p>
                                {% endfor %}
                            </p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>演员：</strong>
                                {% for actor_role in actor_roles %}
                                    <p><a href="{% url 'actor' actor_role.actor.id %}">{{ actor_role.actor.name }}</a>  饰演  {{ actor_role.duty }}</p>
                                {% endfor %}
                                </p>
                        </div>
                    </div>
                                     
                 
                    <p><strong>剧情概述：</strong>{{ movie.intro | slice:240 }}...</p>                 
                    <p><strong>喜欢数量：{{ movie.collect.count }}</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        {% if is_collect %}
                            <a class="button" style="padding: 5px 10px; margin-left: 10px; background-color: grey; color: white;border: 1px solid;" href="{% url 'decollect' movie.id %}">取消喜欢</a>
                        {% else %}
                            <a class="button" style="padding: 5px 10px; margin-left: 10px; background-color: grey; color: white;border: 1px solid;" href="{% url 'collect' movie.id %}">加入喜欢</a>{% endif %}
                            {#                        <button>收藏</button>#}
                    </p>
                    <div class="row">
                        <div class="col-md-6">
                            <p>
                                <strong>电影数据库评分：{{ movie.d_rate }}</strong>&nbsp;&nbsp;&nbsp
                            </p>
                        </div>
                     
                    </div>
                   
                </div>
                <div class="clearfix"></div>
              
                <br><br><br>
            <div>
                <div>
                    {% if user_rate is not None %}
                        <h2 style="margin: 0; padding: 0; display: block; font-size: 1.2em; text-transform: uppercase; font-weight: 700;color: grey;">您的评分: {{ user_rate.mark }}</h2>
                    {% else %}
                        <form action="{% url 'score' movie.id %}" method="post">
                            {% csrf_token %}
                            <strong class="d-inline-block" style="margin-bottom: 0; box-sizing: border-box; margin-right: 20px">
                                <h2>添加评分：</h2>
                                <select name="score" class="custom-select" style="width: auto；margin-bottom: 20px;margin-top: 20px;display: block;">
                                    <option>1.0</option>
                                    <option>2.0</option>
                                    <option>3.0</option>
                                    <option>4.0</option>
                                    <option>5.0</option>
                                    <option>6.0</option>
                                    <option>7.0</option>
                                    <option>8.0</option>
                                    <option>9.0</option>
                                    <option>10.0</option>
                                </select>
                            </strong>
                            <input type="submit"  class="button" id="submit" style="background-color: #c5c5c5;width: 2cm;display: block;" value="提交"/>
                            <!-- <button type="submit" class="download" style="width: 120px;display: block;">提交</button> -->
                        </form>
                    {% endif %}
                </div>
            </div>
                <div class="comment">
                    <div lang="en-US" class="gitment-container gitment-editor-container">
                        <form role="form" class="" action="{% url 'comment' movie.id %}" method="post">
                            <div class="gitment-editor-main">
                                <div class="gitment-editor-header" style="margin-top: 20px;">
                                    <h2>您的影片评论：</h2>
                                    <br>
                                </div>
                                {% csrf_token %}
                                <div class="gitment-editor-body">
                                    <textarea class="text_area" rows="3" cols="80" name="comment" id="comment" tabindex="4" placeholder="请输入评论"></textarea>
                                </div>
                            </div>
                            <div class="gitment-editor-footer">
                                <br><input type="submit" name="submit" class="button" id="submit" style="background-color: #c5c5c5;width: 2cm;" value="发送"/>
                            </div>
                        </form>
                    </div>

                    <div lang="en-US" class="gitment-container gitment-comments-container">
                        <p>----------------------------------------------------------------------------------------------------------</p>
                        <div class="gitment-editor-header">
                            <h2>其他影片评论：</h2>
                            <br>
                        </div>
                        <div class="gitment-comments-list">
                            {% for i in comments %}
                                <li class="gitment-comment">
                                    <a class="gitment-comment-avatar">
                                        <img class="gitment-comment-avatar-img img-circle" src='{{ request.user.email|gravatar:"50" }}'>
                                        <span class="gitment-comment-name"> {{ i.user.username }} 发布于 </span><span>{{ i.create_time }} </span>
                                    </a>
                                    <br>
                                    <div class="gitment-comment-body gitment-markdown"><p>{{ i.content }} </p></div>
                                </li>
                            {% endfor %}

                        </div>

                    </div>

                </div>
            </div>
            <!-- artical-details-info -->
        </div>
        <!-- related-articals -->
        <!-- related-articals -->
        <!-- artical-single-page -->
        <div class="clearfix"></div>
    </div>
{% endblock %}

user/templates/user/director_details.html
<!-- 导演详情界面 -->
{% extends 'base.html' %}
{% load grav_tag %}
{% block content %}
<style>
    .artical-details-info a {
        color: #4cb4cc;
    }
</style>
<div class="col-md-12 content-left">

    <div class="albums">
        <h1>导演详情</h1>
    </div>
    <div class="col-md-8 content-left" style="width: 20%;">
        <img src="{{ MEDIA_URL }}{{ director.image_link }} " style="max-width: 100%;">
    </div>
    <div class="col-md-8 content-right" style="width: 80%;">
        <div class="artical-details">
            <h2>{{ director.name }} </h2>
            <div class="artical-details-info">
                <div class="row">
                    <p><strong>&nbsp;&nbsp;&nbsp;&nbsp;性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：</strong> {{ director.gender }}</p>
                    <p><strong>&nbsp;&nbsp;&nbsp;&nbsp;生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：</strong> {{ director.birthday }}</p>
                    <p><strong>&nbsp;&nbsp;&nbsp;&nbsp;国&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;籍：</strong> {{ director.nationality }}</p>
                    <p><strong>&nbsp;&nbsp;&nbsp;&nbsp;获奖记录：</strong> {{ director.prize }} </p>
                  <p> 
                        <table>
                            <tr>
                                <td style="align-content: flex-start;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;简&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;介：</strong></td>
                                <td> {{ director.introduction }}</td>
                            </tr>
                        </table>
                    </p>
                    <p> 
                        <table>
                            <tr>
                                <td style="align-content: flex-start;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;导演的相关电影：</strong></td>
                                <td> {% for movie in director.movie_set.all %}
                                    <a href="{% url 'movie' movie.id %}">{{ movie.name }}</a>
                                    <br>
                                {% endfor %}</td>
                            </tr>
                        </table>
                    </p>
                </div>
            </div>
        <div class="clearfix"></div>
    </div> 
{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}
{% block right-panel-content %}
    <h2 align="center">User Login</h2>
    <div class="col-md-4 col-md-offset-4">
        <form action="{% url 'login' %}" method='post' autocomplete="on">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field.errors }}
                    {{ field }}
                </div>
            {% endfor %}
            <div class="row">
                <div class="col-md-5 ">
                    <button type="reset" class="btn btn-block btn-danger">Clean</button>
                </div>
                <div class="col-md-5 col-md-offset-2">
                    <button type="submit" class="btn btn-block btn-success">Login</button>

                </div>
            </div>
        </form>
    </div>
{% endblock %}

user/templates/user/my_comment.html
{% extends "user/base_show.html" %}
{% block th_name %}
    <th>Movie Name</th>
    <th>Comment</th>
    <th>Comment Time</th>
    <th>Delete</th>
{% endblock %}
{% block modal %}
    <a class="btn btn-primary" href="{% url 'delete_comment' i.id %}">Confirm</a>

{% endblock %}
{% block th_value %}
    <td>{{ i.movie.name }}</td>
    <td>{{ i.content }}</td>
    <td>{{ i.create_time }}</td>
    <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirm-modal-{{ i.id }}">Delete</a></td>
{% endblock %}